
skillMetadata:
  sections:
    - name: Login
      fields:
        - type: label
          label: The Wyze Thermostat skill needs your Wyze account login info to access your thermostat via Mycroft.
        - name: wyze_username
          type: email
          label: E-mail for Wyze account
          value: ""
        - name: wyze_password
          type: password
          label: Password
          value: ""
